- id: '1609213001'
  alias: Start HomeKit
  trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
  - platform: event
    event_type: zwave.network_complete_some_dead
  action:
  - service: homekit.start
- id: '1575141383597'
  alias: Night Lights On
  description: Turn on the lights at sunset
  trigger:
  - event: sunset
    platform: sun
    offset: -01:00
  condition: []
  action:
  - data:
      brightness_pct: 20
    service: homeassistant.turn_on
    target:
      entity_id: light.stair_lights
  - data:
      brightness_pct: 25
    service: homeassistant.turn_on
    target:
      entity_id: light.entrance_lights
  - data:
      brightness_pct: 60
    service: homeassistant.turn_on
    target:
      entity_id:
      - light.porch_lights
      - light.driveway_side
  mode: single
- id: '1575141770149'
  alias: Night Lights Off
  description: Turn off the lights at sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data: {}
    service: homeassistant.turn_off
    target:
      entity_id:
      - light.stair_lights
      - light.entrance_lights
      - light.porch_lights
      - light.driveway_side
  mode: single
- id: '1577677205027'
  alias: Kitchen Lights 10%
  description: Turn on the kitchen lights with motion
  trigger:
  - entity_id: binary_sensor.kitchen_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
    - condition: time
      after: 01:00:00
      before: 00:00:00
    - condition: sun
      before: sunrise
  action:
  - data:
      brightness_pct: 10
    service: homeassistant.turn_on
    target:
      entity_id: light.kitchen_lights
  mode: single
- id: '1577677822873'
  alias: Kitchen Lights Off
  description: Turn off when no motion is detected
  trigger:
  - entity_id: binary_sensor.kitchen_motion_sensor
    for: 00:20:10
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    service: homeassistant.turn_off
    target:
      entity_id:
      - light.kitchen_lights
      - light.family_room
  mode: single
- id: '1577858799562'
  alias: Dining Light On
  description: Turn on the dining room light with motion
  trigger:
  - entity_id: binary_sensor.dining_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.dining_room_light
      state: 'off'
    - condition: or
      conditions:
      - after: sunset
        after_offset: -02:00:00
        condition: sun
      - before: sunrise
        before_offset: +02:00:00
        condition: sun
  action:
  - data:
      brightness_pct: 20
    service: homeassistant.turn_on
    target:
      entity_id: light.dining_room_light
  mode: single
- id: '1577858907155'
  alias: Dining Lights Off
  description: Turn off the dining room lights when no motion is detected
  trigger:
  - entity_id: binary_sensor.dining_motion_sensor
    for: 00:10:10
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.dining_room_light
    service: homeassistant.turn_off
  mode: single
- id: '1584326906110'
  alias: Lights On at Sunset
  description: Turn on lights at offset
  trigger:
  - event: sunset
    offset: -02:00:00
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 65
    entity_id: light.kennys_lamp
    service: light.turn_on
  - data:
      brightness_pct: 65
    entity_id: light.sabrinas_lamp
    service: light.turn_on
  - data:
      brightness_pct: 65
    entity_id: light.table_left
    service: light.turn_on
  - data:
      brightness_pct: 65
    entity_id: light.table_right
    service: light.turn_on
  - data:
      brightness_pct: 65
    entity_id: light.floor_left
    service: light.turn_on
  - data:
      brightness_pct: 65
    entity_id: light.floor_right
    service: light.turn_on
  mode: single
- id: '1584327993330'
  alias: Master Lights Off
  description: Turn off the master lights when nobody is home
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.sabrina
      state: not_home
    - condition: state
      entity_id: person.kenny_speer
      state: not_home
  action:
  - entity_id: light.kennys_lamp
    service: light.turn_off
  - entity_id: light.sabrinas_lamp
    service: light.turn_off
- id: '1597551289197'
  alias: Fan On at Night
  description: Turn on the upstairs fan at 9pm
  trigger:
  - at: '20:15:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.upstairs
      fan_min_on_time: 60
    entity_id: climate.upstairs
    service: ecobee.set_fan_min_on_time
  - data:
      fan_min_on_time: 60
      entity_id: 'climate.downstairs '
    service: ecobee.set_fan_min_on_time
  mode: single
- id: '1597551452597'
  alias: Fan Off in Morning
  description: Turn off the upstairs fan at 6am
  trigger:
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.upstairs
      fan_min_on_time: 0
    entity_id: climate.upstairs
    service: ecobee.set_fan_min_on_time
  - data:
      entity_id: climate.downstairs
      fan_min_on_time: 0
    service: ecobee.set_fan_min_on_time
  mode: single
- id: '1609298626424'
  alias: Gym Light On
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: homeassistant.turn_on
    data: {}
    entity_id: switch.gym_light
  mode: single
- id: '1609298776809'
  alias: Gym Light Off
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor
    to: 'off'
    for: 00:25:10
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    entity_id: switch.gym_light
  mode: single
- id: '1619809018468'
  alias: Office Lights On
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 24af8e197022ed4bd5c3107052d73eb6
    entity_id: binary_sensor.office_motion_sensor
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: light.office_ceiling_light
    state: 'off'
  action:
  - data:
      brightness_pct: 32
    service: light.turn_on
    target:
      entity_id: light.office_ceiling_light
  mode: single
- id: '1619818850342'
  alias: Office Lights Off
  description: ''
  trigger:
  - type: turned_off
    platform: device
    device_id: 24af8e197022ed4bd5c3107052d73eb6
    entity_id: binary_sensor.office_motion_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.office_ceiling_light
    data: {}
  mode: single
- id: '1630288053809'
  alias: Night Lights Dim
  description: Adjust lights after sunset
  trigger:
  - event: sunset
    offset: +01:00
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 17
    service: homeassistant.turn_on
    target:
      entity_id:
      - light.entrance_lights
      - light.stair_lights
  - data:
      brightness_pct: 25
    service: homeassistant.turn_on
    target:
      entity_id:
      - light.porch_lights
      - light.driveway_side
  mode: single
- id: '1630288843753'
  alias: Night Lights Porch Off
  description: Porch Lights Off @ 10:30 PM
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - service: homeassistant.turn_off
    target:
      entity_id:
      - light.porch_lights
      - light.entrance_lights
      - light.driveway_side
    data: {}
  mode: single
- id: '1635215327717'
  alias: Kitchen Lights 30%
  description: Turn on the kitchen lights with motion
  trigger:
  - entity_id: binary_sensor.kitchen_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
    - condition: or
      conditions:
      - condition: time
        before: 01:00:00
        after: 00:00:00
      - condition: sun
        after: sunset
  action:
  - data:
      brightness_pct: 30
    service: homeassistant.turn_on
    target:
      entity_id: light.kitchen_lights
  mode: single
- id: '1635635334662'
  alias: Kitchen Lights 60%
  description: Turn on the kitchen lights with motion
  trigger:
  - entity_id: binary_sensor.kitchen_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
  action:
  - data:
      brightness_pct: 60
    service: homeassistant.turn_on
    target:
      entity_id: light.kitchen_lights
  mode: single
