version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    network_mode: host
    restart: always
    volumes:
      - /volume1/ksfs/k8s_data/ha-config:/config
      - /volume1/ksfs/k8s_data/certbot:/certbot
      - /usr/builtin/etc/certificate:/etc/certificate
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - 8123:8123
      - 51827:51827

  proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: nginx
    networks:
      - ha-net
    restart: always
    depends_on:
      - homeassistant
    volumes:
      - /volume1/ksfs/k8s_data/apps/nginx:/etc/nginx
      - /usr/builtin/etc/certificate:/etc/certificate
    ports:
      - 8443:443

networks:
  ha-net:
