version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:stable
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /data/ha-config:/config
      - /data/certbot:/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - 8123:8123

  reverse:
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: nginx
    restart: always
    network_mode: host
    ports:
      - 8443:443
    volumes:
      - /data/apps/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
