version: '3.1'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant:latest
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /data/ha-config:/config
      - /data/certbot:/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123

  zwavejs:
    container_name: zwavejs
    hostname: zwavejs
    image: zwavejs/zwave-js-ui:latest
    restart: always
    network_mode: host
    volumes:
      - /data/ha-config/zwave:/usr/src/app/store
    devices:
      - /dev/ttyACM0:/dev/zwave
    ports:
      - 3000:3000
      - 8091:8091
