version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:latest
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /data/ha-config:/config
      - /data/certbot:/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
#    devices:
#      - /dev/ttyACM0

  nginx:
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: nginx:latest
    restart: always
    network_mode: host
    ports:
      - 443:443
    volumes:
      - /data/apps/nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt

  zwavejs:
    container_name: zwavejs
    hostname: zwavejs
    image: zwavejs/zwave-js-ui:latest
    restart: always
    network_mode: host
    volumes:
      - /data/ha-config/zwave:/usr/src/app/store
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/zwave
    ports:
      - 3000:3000
      - 8091:8091
